version: '2'
services:
  db:
    image: mysql:5.7.17
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
